os:
  - linux
  - linux-ppc64le

language: java
sudo: false

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux-ppc64le
    jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

script:
- ./mvnw test
- ./mvnw javadoc:aggregate
