os: linux
language: java
sudo: false

jdk:
  - oraclejdk8

matrix:
  include:
  - os: linux-ppc64le
    jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

script:
- ./mvnw test
- ./mvnw javadoc:aggregate
